dev

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,8 +17,14 @@ jobs:
 # shader workaround - prepare
     - name: Shaders Workaround (prepare)
       run: |
-        zip -r shaders.zip assets/minecraft/shaders
-        rm -r assets/minecraft/shaders
+        ls -la assets/minecraft/shaders || echo "Directory not found"
+        if [ -d assets/minecraft/shaders ]; then
+          zip -r shaders.zip assets/minecraft/shaders
+          rm -r assets/minecraft/shaders
+        else
+          echo "Shaders directory not found or empty"
+          exit 1
+        fi
 
 # build -> fetch -> rename
     - name: Build
